version: "3.8"
services:
  meu-redis:
    image: redis:latest
    ports:
    - 6379:6379
    environment:
    - REDIS_PASSWORD
    - REDIS_APPENDONLY
    env_file: .env
    volumes:
      - redis_data:/data
    restart: unless-stopped

volumes:
  redis_data:
